avahi.lo: /usr/src/avahi/avahi.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/usr/src/avahi $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /usr/src/avahi/avahi.c -o avahi.lo 
$(phplibdir)/avahi.la: ./avahi.la
	$(LIBTOOL) --mode=install cp ./avahi.la $(phplibdir)

./avahi.la: $(shared_objects_avahi) $(AVAHI_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_avahi) $(AVAHI_SHARED_LIBADD)

